name: build-test

on:
  push:
    branches: ["develop/**", "feature/**"]
    paths: 
      - "MPCDriving/**"
      - ".github/workflows/mpc_driving.yaml"
  pull_request:
    branches: ["main"]

env:
  BUILD_TYPE: Debug

jobs:
  mpc_driving:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
    container:
      image: ghcr.io/cmaybe/dev-mpc-driving:latest
      options: --user root
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure CMake
        run: |
          cmake \
            -S ./MPCDriving \
            -B ./MPCDriving/build \
            -G "Unix Makefiles" \
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: |
          cmake \
            --build ./MPCDriving/build \
            --config ${{env.BUILD_TYPE}} \
            --target install

      - name: Configure example
        run: |
          cmake \
            -S ./examples/mpc \
            -B ./examples/mpc/build \
            -G "Unix Makefiles" \
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: |
          cmake \
            --build ./examples/mpc/build \
            --config ${{env.BUILD_TYPE}}

